services:
  django:
    image: django
    container_name: django
    build:
      context: ./back
    volumes:
      - ./back/:/usr/src/app
    ports:
      - "8000:8000"
    env_file: ./back/.env
    depends_on:
      - db_postgres
      - redis
    networks:
      - app_network

  db_postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./database
    ports:
      - "5432:5432"
    env_file: ./database/.env
    restart: always
    networks:
      - app_network

  react:
    image: react
    container_name: react
    build:
      context: ./front
    # ports:
    #   - "5173:5173"
    volumes:
      - ./front/frontend/:/app
    env_file: ./front/frontend/.env
    restart: always
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      # - "9280:80"      # HTTP
      - "9443:443"    # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - django
      - react
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
