# Generated by Django 5.1.5 on 2025-02-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_player_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
